-- This mod allows all non-fluid items to be sent via delivery cannon
-- We populate the tables in data-updates.lua to catch items from other mods
-- Empty data.lua to satisfy mod structure requirements
